"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Atom, Clock3, FlaskConical, LockKeyhole, Play, Sigma } from "lucide-react";

import { simulations } from "@/data/platform";

const icons = { physics: Atom, chemistry: FlaskConical, mathematics: Sigma };

export function SimulationGallery() {
  const [filter, setFilter] = useState<"all" | "physics" | "chemistry" | "mathematics">("all");
  const filtered = simulations.filter((simulation)=>filter==='all'||simulation.subjectId===filter);
  return <div className="content-shell pb-28 pt-8 lg:pb-14 lg:pt-10"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mono-kicker">05 — Concept lab</p><h2 className="mt-4 font-display text-3xl font-bold sm:text-4xl">Make the equation move.</h2><p className="mt-3 max-w-2xl text-[#C7C5CC]">Change one variable, predict the result, and see whether your intuition survives the model.</p></div><div className="flex flex-wrap gap-2">{(['all','physics','chemistry','mathematics'] as const).map((item)=><button className={`min-h-11 border px-4 text-sm font-semibold capitalize ${filter===item?'border-[#FF5A1F] bg-[#FF5A1F]/8 text-white':'border-white/10 text-[#C7C5CC]/80'}`} key={item} onClick={()=>setFilter(item)} type="button">{item}</button>)}</div></div><div className="mt-9 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((simulation,index)=>{const Icon=icons[simulation.subjectId];const live=simulation.availability==='live';return <article className={`group relative overflow-hidden border bg-[#161418] p-6 ${live?'border-[#FF5A1F]/45 shadow-[0_0_50px_rgba(255,90,31,.08)]':'border-[#FF5A1F]/18'}`} key={simulation.id}><div className="absolute -right-16 -top-16 size-40 rounded-full border border-[#FF5A1F]/15"/><div className="absolute -right-7 -top-7 size-24 rounded-full border border-[#FF5A1F]/12"/><div className="relative flex items-start justify-between"><div className="grid size-12 place-items-center border border-[#FF5A1F]/25 text-[#FF8A3D]"><Icon size={22} strokeWidth={1.5}/></div><span className={`flex items-center gap-2 font-mono text-[11px] uppercase tracking-[.13em] ${live?'text-[#3DE08A]':'text-[#C7C5CC]/70'}`}>{live?<><span className="size-2 bg-[#3DE08A]"/>Live</>:<><LockKeyhole size={12}/>Soon</>}</span></div><p className="mono-kicker mt-9">{String(index+1).padStart(2,'0')} · {simulation.subjectId}</p><h3 className="mt-3 font-display text-2xl font-semibold">{simulation.title}</h3><p className="mt-3 min-h-20 text-sm leading-6 text-[#C7C5CC]/80">{simulation.description}</p><div className="mt-6 flex items-center justify-between border-t border-white/8 pt-5"><span className="flex items-center gap-2 font-mono text-[11px] text-[#C7C5CC]/70"><Clock3 size={13}/>{simulation.estimatedMinutes} MIN</span><Link className={`inline-flex min-h-11 items-center gap-2 text-sm font-bold ${live?'text-[#FF8A3D]':'text-[#C7C5CC]/70'}`} href={`/simulations/${simulation.slug}`}>{live?<><Play size={15}/>Launch</>:<>Preview<ArrowRight size={15}/></>}</Link></div></article>})}</div></div>;
}
